general:
  input_folder: '/home/datascience/local_input_folder'
  output_folder: '/home/datascience/local_output_folder'
  clean_output_folder: false
  run_sematic_segmentation: true
  run_instance_segmentation: false
label_formats:
  label_for_instances_in_gt: 'treeID'
  label_for_instances_in_predicted: 'instance_nr'
semantic_segmentation_params:
  sematic_segmentation_script: './run_bash_scripts/sem_seg_sean.sh'
  checkpoint_model_path: './fsct/model/model.pth'
  batch_size : 5 # batch size for inference
  tile_size: 10 # tile size in meters
  min_density: 100 # minimum density of points in a tile(used for removing small tiles)
  remove_small_tiles: 0 # 1: remove small tiles, 0: not remove small tiles
instance_segmentation_params:
  instance_segmentation_script: './run_bash_scripts/tls.sh' 
  n_tiles: 3
  slice_thickness: 0.5
  find_stems_height: 1.5
  find_stems_thickness: 0.5
  graph_maximum_cumulative_gap: 3
  add_leaves_voxel_length: 0.5
  find_stems_min_points: 50
  graph_edge_length: 1.0
  add_leaves_edge_length: 1.0