general:
  input_folder: 'some_path'
  output_folder: 'some_path'
  run_sematic_segmentation: true
  run_instance_segmentation: false
label_formats:
  label_for_instances_in_gt: 'treeID'
  label_for_instances_in_predicted: 'instance_nr'
semantic_segmentation_params:
  first: 'some'
